- name: Deploy docker compose files
  hosts: maven-servers
  become: yes
  tasks:
   - name: Update apt cache
     apt:
       update_cache: yes

# from https://www.digitalocean.com/community/tutorials/how-to-use-ansible-to-install-and-set-up-docker-on-ubuntu-20-04#step-4-adding-docker-image-and-container-tasks-to-your-playbook
   - name: Install aptitude
     apt:
        name: aptitude
        state: latest
     become: true

   - name: Install required system packages
     apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
     become: true

   - name: Add Docker GPG apt Key
     apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
     become: true

   - name: Add Docker Repository
     apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present
     become: true

   - name: Update apt and install docker-ce
     apt:
      name: docker-ce
      state: latest
     become: true

   - name: Create ghactions user
     user:
        name: ghactions
        state: present
        shell: /bin/bash

   - name: Add ghactions user to docker group
     user:
        name: ghactions
        groups: docker
        append: yes

   - name: Ensure Docker service is enabled and running
     service:
        name: docker
        state: started
        enabled: yes

   - name: Tear down existing services
     community.docker.docker_compose_v2:
       project_src: reposilite
       state: absent

   - name: Create and start services
     community.docker.docker_compose_v2:
       project_src: reposilite
     register: output

   - name: Show results
     ansible.builtin.debug:
       var: output
